# Generated by Django 2.2.6 on 2019-10-26 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('following_count', models.PositiveIntegerField()),
                ('follower_count', models.PositiveIntegerField()),
                ('gists_count', models.PositiveIntegerField()),
                ('avatar_url', models.URLField(max_length=500, unique=True)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=4000)),
                ('languages', models.TextField(max_length=1000)),
                ('stars', models.PositiveIntegerField()),
                ('watchers', models.PositiveIntegerField()),
                ('commit_history_week_wise', models.TextField(max_length=1000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='devfaceoff.Developer')),
            ],
        ),
    ]
